//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazyn
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cable()
        {
            this.Logs = new HashSet<Log>();
        }
        
        public int CableId { get; set; }
        [Required]
        public string CableName { get; set; }
        [StringLength(30)]
        public string CablePN { get; set; }
        [Range(0, int.MaxValue, ErrorMessage ="Wartoœæ zamówionej iloœci musi byæ liczb¹ nieujemn¹")]
        public Nullable<int> OrderedQty { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        public int MinStock { get; set; }
        //[RegularExpression(@"^\$?\d+(\.(\d{2}))?$")]
        public decimal Price { get; set; }
        public byte[] Image { get; set; }
        [StringLength(30)]
        public string Desc { get; set; }
        [Required]
        [Range(0, int.MaxValue)]
        public int Stock { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Log> Logs { get; set; }
    }
}
